repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        exclude: ^modules/aws-ecs-
        args:
          - '--args=--lockfile=false'
          - '--hook-config=--use-standard-markers=true'
      - id: terraform_tflint
        args:
          - '--args=--config=__GIT_WORKING_DIR__/.tflint.hcl'
