formatter: "markdown table"

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules
  include-main: true

sections:
  hide: []

content: |-
  
  # Upwind AWS Organization Onboarding Terraform module
  This module defines the IAM roles, policies and resources necessary to onboard the accounts of an AWS Organization
  into to Upwind. Rather than attempting to deploy the resources into multiple accounts, the module has been defined
  such that it can be readily integrated into IaC tools such as Terragrunt, which are much more capable of deploying 
  the resources at scale across multiple accounts.
  The structure of the terraform in this module is as follows:
  * top level conditional logic which creates the resources based on account type.
  * sub modules - one for each resource. These should be reasonably self contained units which could be run separately
    if desired.
  ## Organization Onboarding Process
  The goal of the onboarding process is to connect all the necessary accounts within your AWS organization into Upwind, allowing 
  Upwind to perform security audits and scans on those accounts as necessary.
  The process can be initiated through the Upwind console which guides the user through the process, before applying 
  this module to the accounts to create the necessary IAM roles and polices etc.
  Once onboarded, it will be possible to inspect the accounts from inside the Upwind console.
  ![image info](.docs/AWSOrgScreenshot1.png) 
  ## Account Types
  Notionally the onboarding process takes 3 account types into consideration.
  * Management account: An account with delegated permissions which should be used to manage the remaining accounts within the on: 
    Organization. In the context of the Upwind onboarding process, this account is used 
    to discover additional details about the AWS organization - eg the accounts.
  * Orchestrator Account: The orchestrator account is regarded as a special account and is the account in which
    Upwind will orchestrator its scanning activities - creating the CloudScanner resources as necessary.
  * Other accounts: The remaining accounts should be connected as these are accounts which are assumed to need protected
    whether through auditing or scanning.
  ## Roles and IAM Policies
  The module defines a number of IAM roles and policies, some of which can be assumed from the upwind SaaS for the use cases 
  described below.
  ### Trusted Entity
  Any role that can be assume from Upwind has includes an trusted entity similar to the following example.
  ``` json
  {{ include ".docs/trusted-entity.json" }}
  ```
  The external-id will be provided by Upwind as part of the onboarding processes.
  ### Organization Discovery role
  The Organization discovery role is a read only role which can be assumed and is used to discover the accounts within
  the AWS organization. It is assumed by Upwind to discover the accounts and account structure within the AWS organization.
  The definition for the role can be found in the iam_organization_service_role submodule, and its creation is conditional so that the role is only created in
  management account.
  > [!TIP]
  > The Organization Discovery role only needs to be created in the management account.
  ### Account Service role
  The Account Service role, for the most part is a role that grants, and is assumed from Upwind for read only and audit access to the account, and which can be created
  in all accounts. In the orchestrator account, if one is selected, the role contain elevated permissions which allows the it to used 
  for the installation of CloudScanners.
  This role is defined in the iam_account_service_role submodule.
  > [!TIP]
  > This Account Service role should be created in all accounts which are to be audited or scanned - which may optionally include the management account. If configuring 
  > an orchestrator account the Account Service role must be created in the account with the elevated permissions.
  ### CloudScanner Administrator role
  This role is only created in the orchestrator account - if one has been defined. It is the roll granted to the 
  CloudScanner resources (Lambda's, ASG and EC2 instances) allowing them to function.
  Note: Removing this role while it has attached resources (eg CloudScanners) should be avoided, as it is connected to these resources.
  The definition for the role can be found in the iam_cloudscanner_admin_role.
  > [!TIP]
  > The CloudScanner admin role must be created in the orchestrator account if one has been selected.
  ### CloudScanner Execution role
  This role grants the necessary permissions to allows the CloudScanner to perform cross account scans from the orchestrator account. Specifically,
  the role can be assumed by the CloudScanner in the orchestrator account and can be used to create resources such as disk snapshots and fetch lambdas from accounts other 
  than the orchestrator account.
  The role is defined in the iam_cloudscanner_execution_role submodule.
  > [!TIP]
  > The CloudScanner Execution role should be installed in all accounts which are to be scanned. 
  
  ### Organization Discovery Role Registration
  When being run in the management account, the module will attempt to register the Organization discovery role once the role has been created. This process makes an authenticated request to the 
  Upwind SaaS passing the ARN of the Organization Discovery role, which in turn initiates the onboarding process within the Upwind backend end systems. This process firsts discovers the accounts 
  in the organization, presenting them to the user within the Upwind Web console. From here the user can define additional scopes for the respective accounts etc.
  The Upwind backend will continue to connect accounts as they are onboard, discovering resources, and if an orchestrator account has been configured, will install CloudScanners as scannable targets 
  (eg VMs, lambdas etc.) are discovered.
  
  > [!TIP]
  > If its not possible to connect to the internet from you IAC system, this option can be disabled, but the Discovery role ARN will need to be provided to Upwind technical support in order to enter 
  > into the system manually. This can be disabled as per the example below.
  ## CloudScanners
  Shortly after the onboarding has completed, CloudScanners will be automatically installed into the orchestrator account, 
  one per region which has scannable resources within all of the accounts.
  Each CloudScanner includes a number of resources include AWS Lambdas and Auto Scaling groups which are used to scaler
  a number of VM (workers) to perform the scans.
  ## Integration Guidelines
  By default the module should contain all of the necessary logic such that it can be integrated into your IaC tool and apply
  to all of the accounts within your AWS org. It should be possible to include the same variables/parameters into for each account, and doing this would be the preferred
  method. However the module has been organized so that if required the resources can be separated out and more readily integrated into you IAC.
  When doing so following guidelines should be followed.
  ### Resource Naming and Tags
  By default the module provides default names for each of the resources - even allowing for small random suffix
  to be appended to the end of each name. 
  These names can be changed to align with your own naming conventions. However it is important that the same name for a given role function is used consistently
  across all accounts and that the role names are set as defined in the submodules. The tags are used to help discover the role names and other resources created during on boarding.
  When renaming a role - the name must be consistent in all accounts.
  ### Authentication Secrets
  By default the module can either accept the secret clientId and secret value - or a secret ARN containing the generated 
  values. If creating an ARN the values should be stored within the secret as follows:
  ```json
  {
    "clientId": "<<client-id>>",
    "clientSecret": "<<client-secret>>"
  }
  ```
  You will need to ensure that the ARN is accessible across all regions, and if using non-default KMS keys to protect
  the secret, that these are readily accessible - tailoring the roles if necessary.
  ### Custom Tags
  Custom tags can be added to the module, and these will be applied to every resource created by the module - IAM roles and policies, and secrets.
  ## Examples
  The following example of the module which can be applied to all accounts to create the roles as described above. This example defines the variable
  install_roles_in_management_account which means the module will install the Account Service and CloudScanner Execution roles in the management account.
  ```hcl
  {{ include ".docs/example1.tff" }}
  ```
  
  The following example shows how to disable the org discovery role registration process. Given the addition variables including credentials are no longer needed,
  they have also been removed from this example.
  ```hcl
  {{ include ".docs/example2.tff" }}
  ```
  
  The following example is comparable to the first, but shows how to inject the alternative role names into the module. This would be the preferred method for changing roles
  as should ensure continuity across all accounts, although it is recommended to choose more appropriate values that those in this example. The example also illustrates on
  custom tags can be applied to the module:
  ```hcl
  {{ include ".docs/example3.tff" }}
  ```
  {{ .Header }}
  {{ .Providers }}
  {{ .Outputs }}
  {{ .Inputs }}
  {{ .Resources }}
output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->    
output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true